name: CICD

on:
  push:

permissions:
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: github/codeql-action/init@v3
      with:
        languages: csharp
        build-mode: manual
    
    
    - run: dotnet build

    - uses: github/codeql-action/analyze@v3
