name: CICD

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: github/codeql-action/init@v3
    
    - run: dotnet build

    - uses: github/codeql-action/analyze@v3
